### PR TITLE
iter++ iter-- bugfix

### PR DESCRIPTION
**Pull request by LightningBilly**
find some bugs about iter++ iter--, and fix

### CODE REVIEW

**Review by dwd — APPROVED** [review]

**Comment by dwd** [comment]
You happy with the licences?

**Comment by LightningBilly** [comment]
find some bugs about iter++ iter--, and fix

**Comment by LightningBilly** [comment]
I'am happy with the licensing.

**Comment by dwd** [comment]
Thanks!

**Pull request merged**
